# Generated by Django 6.0.6 on 2026-07-09 18:29

from django.db import migrations, models


def remove_contact_original_price_if_exists(apps, schema_editor):
    if schema_editor.connection.vendor != 'sqlite':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('PRAGMA table_info(swiftcart_contact)')
        columns = [row[1] for row in cursor.fetchall()]
        if 'original_price' in columns:
            cursor.execute('ALTER TABLE swiftcart_contact DROP COLUMN original_price')


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcart', '0006_contact'),
    ]

    operations = [
        migrations.RunPython(
            remove_contact_original_price_if_exists,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
