# Generated by Django 6.0.5 on 2026-07-11 07:29

from django.db import migrations, models


def remove_stale_columns_if_present(apps, schema_editor):
    if schema_editor.connection.vendor != 'sqlite':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute('PRAGMA table_info(swiftcart_contact)')
        contact_columns = {row[1] for row in cursor.fetchall()}
        if 'original_price' in contact_columns:
            cursor.execute('ALTER TABLE swiftcart_contact DROP COLUMN original_price')

        cursor.execute('PRAGMA table_info(swiftcart_product)')
        product_columns = {row[1] for row in cursor.fetchall()}
        if 'discount' in product_columns:
            cursor.execute('ALTER TABLE swiftcart_product DROP COLUMN discount')


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcart', '0007_remove_contact_original_price_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RunPython(
            remove_stale_columns_if_present,
            migrations.RunPython.noop,
        ),
    ]
