# Generated by Django 6.0.5 on 2026-07-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftcart', '0009_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
    ]
